package com.feicui365.live.util;


import com.feicui365.live.R;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;


public class FaceUtil {

    private static final Map<String, Integer> FACE_MAP;

    private static final List<String> FACE_LIST;

    static {
        FACE_MAP = new LinkedHashMap<>();
        FACE_MAP.put("[NO]", R.mipmap.face_001);
        FACE_MAP.put("[OK]", R.mipmap.face_002);
        FACE_MAP.put("[下雨]", R.mipmap.face_003);
        FACE_MAP.put("[么么哒]", R.mipmap.face_004);
        FACE_MAP.put("[乒乓]", R.mipmap.face_005);
        FACE_MAP.put("[便便]", R.mipmap.face_006);
        FACE_MAP.put("[信封]", R.mipmap.face_007);
        FACE_MAP.put("[偷笑]", R.mipmap.face_008);
        FACE_MAP.put("[傲慢]", R.mipmap.face_009);
        FACE_MAP.put("[再见]", R.mipmap.face_010);
        FACE_MAP.put("[冷汗]", R.mipmap.face_011);
        FACE_MAP.put("[凋谢]", R.mipmap.face_012);
        FACE_MAP.put("[刀]", R.mipmap.face_013);
        FACE_MAP.put("[删除]", R.mipmap.face_014);
        FACE_MAP.put("[勾引]", R.mipmap.face_015);
        FACE_MAP.put("[发呆]", R.mipmap.face_016);
        FACE_MAP.put("[发抖]", R.mipmap.face_017);
        FACE_MAP.put("[可怜]", R.mipmap.face_018);
        FACE_MAP.put("[可爱]", R.mipmap.face_019);
        FACE_MAP.put("[右哼哼]", R.mipmap.face_020);
        FACE_MAP.put("[右太极]", R.mipmap.face_021);
        FACE_MAP.put("[右车头]", R.mipmap.face_022);
        FACE_MAP.put("[吐]", R.mipmap.face_023);
        FACE_MAP.put("[吓]", R.mipmap.face_024);
        FACE_MAP.put("[咒骂]", R.mipmap.face_025);
        FACE_MAP.put("[咖啡]", R.mipmap.face_026);
        FACE_MAP.put("[啤酒]", R.mipmap.face_027);
        FACE_MAP.put("[嘘]", R.mipmap.face_028);
        FACE_MAP.put("[回头]", R.mipmap.face_029);
        FACE_MAP.put("[困]", R.mipmap.face_030);
        FACE_MAP.put("[坏笑]", R.mipmap.face_031);
        FACE_MAP.put("[多云]", R.mipmap.face_032);
        FACE_MAP.put("[大兵]", R.mipmap.face_033);
        FACE_MAP.put("[大哭]", R.mipmap.face_034);
        FACE_MAP.put("[太阳]", R.mipmap.face_035);
        FACE_MAP.put("[奋斗]", R.mipmap.face_036);
        FACE_MAP.put("[奶瓶]", R.mipmap.face_037);
        FACE_MAP.put("[委屈]", R.mipmap.face_038);
        FACE_MAP.put("[害羞]", R.mipmap.face_039);
        FACE_MAP.put("[尴尬]", R.mipmap.face_040);
        FACE_MAP.put("[左哼哼]", R.mipmap.face_041);
        FACE_MAP.put("[左太极]", R.mipmap.face_042);
        FACE_MAP.put("[左车头]", R.mipmap.face_043);
        FACE_MAP.put("[差劲]", R.mipmap.face_044);
        FACE_MAP.put("[弱]", R.mipmap.face_045);
        FACE_MAP.put("[强]", R.mipmap.face_046);
        FACE_MAP.put("[彩带]", R.mipmap.face_047);
        FACE_MAP.put("[彩球]", R.mipmap.face_048);
        FACE_MAP.put("[得意]", R.mipmap.face_049);
        FACE_MAP.put("[微笑]", R.mipmap.face_050);
        FACE_MAP.put("[心碎了]", R.mipmap.face_051);
        FACE_MAP.put("[快哭了]", R.mipmap.face_052);
        FACE_MAP.put("[怄火]", R.mipmap.face_053);
        FACE_MAP.put("[怒]", R.mipmap.face_054);
        FACE_MAP.put("[惊恐]", R.mipmap.face_055);
        FACE_MAP.put("[惊讶]", R.mipmap.face_056);
        FACE_MAP.put("[憨笑]", R.mipmap.face_057);
        FACE_MAP.put("[手枪]", R.mipmap.face_058);
        FACE_MAP.put("[打哈欠]", R.mipmap.face_059);
        FACE_MAP.put("[抓狂]", R.mipmap.face_060);
        FACE_MAP.put("[折磨]", R.mipmap.face_061);
        FACE_MAP.put("[抠鼻]", R.mipmap.face_062);
        FACE_MAP.put("[抱抱]", R.mipmap.face_063);
        FACE_MAP.put("[抱拳]", R.mipmap.face_064);
        FACE_MAP.put("[拳头]", R.mipmap.face_065);
        FACE_MAP.put("[挥手]", R.mipmap.face_066);
        FACE_MAP.put("[握手]", R.mipmap.face_067);
        FACE_MAP.put("[撇嘴]", R.mipmap.face_068);
        FACE_MAP.put("[擦汗]", R.mipmap.face_069);
        FACE_MAP.put("[敲打]", R.mipmap.face_070);
        FACE_MAP.put("[晕]", R.mipmap.face_071);
        FACE_MAP.put("[月亮]", R.mipmap.face_072);
        FACE_MAP.put("[棒棒糖]", R.mipmap.face_073);
        FACE_MAP.put("[汽车]", R.mipmap.face_074);
        FACE_MAP.put("[沙发]", R.mipmap.face_075);
        FACE_MAP.put("[流汗]", R.mipmap.face_076);
        FACE_MAP.put("[流泪]", R.mipmap.face_077);
        FACE_MAP.put("[激动]", R.mipmap.face_078);
        FACE_MAP.put("[灯泡]", R.mipmap.face_079);
        FACE_MAP.put("[炸弹]", R.mipmap.face_080);
        FACE_MAP.put("[熊猫]", R.mipmap.face_081);
        FACE_MAP.put("[爆筋]", R.mipmap.face_082);
        FACE_MAP.put("[爱你]", R.mipmap.face_083);
        FACE_MAP.put("[爱心]", R.mipmap.face_084);
        FACE_MAP.put("[爱情]", R.mipmap.face_085);
        FACE_MAP.put("[猪头]", R.mipmap.face_086);
        FACE_MAP.put("[猫咪]", R.mipmap.face_087);
        FACE_MAP.put("[献吻]", R.mipmap.face_088);
        FACE_MAP.put("[玫瑰]", R.mipmap.face_089);
        FACE_MAP.put("[瓢虫]", R.mipmap.face_090);
        FACE_MAP.put("[疑问]", R.mipmap.face_091);
        FACE_MAP.put("[白眼]", R.mipmap.face_092);
        FACE_MAP.put("[皮球]", R.mipmap.face_093);
        FACE_MAP.put("[睡觉]", R.mipmap.face_094);
        FACE_MAP.put("[磕头]", R.mipmap.face_095);
        FACE_MAP.put("[示爱]", R.mipmap.face_096);
        FACE_MAP.put("[礼品袋]", R.mipmap.face_097);
        FACE_MAP.put("[礼物]", R.mipmap.face_098);
        FACE_MAP.put("[篮球]", R.mipmap.face_099);
        FACE_MAP.put("[米饭]", R.mipmap.face_100);
        FACE_MAP.put("[糗大了]", R.mipmap.face_101);
        FACE_MAP.put("[红双喜]", R.mipmap.face_102);
        FACE_MAP.put("[红灯笼]", R.mipmap.face_103);
        FACE_MAP.put("[纸巾]", R.mipmap.face_104);
        FACE_MAP.put("[胜利]", R.mipmap.face_105);
        FACE_MAP.put("[色]", R.mipmap.face_106);
        FACE_MAP.put("[药]", R.mipmap.face_107);
        FACE_MAP.put("[菜刀]", R.mipmap.face_108);
        FACE_MAP.put("[蛋糕]", R.mipmap.face_109);
        FACE_MAP.put("[蜡烛]", R.mipmap.face_110);
        FACE_MAP.put("[街舞]", R.mipmap.face_111);
        FACE_MAP.put("[衰]", R.mipmap.face_112);
        FACE_MAP.put("[西瓜]", R.mipmap.face_113);
        FACE_MAP.put("[调皮]", R.mipmap.face_114);
        FACE_MAP.put("[象棋]", R.mipmap.face_115);
        FACE_MAP.put("[跳绳]", R.mipmap.face_116);
        FACE_MAP.put("[跳跳]", R.mipmap.face_117);
        FACE_MAP.put("[车厢]", R.mipmap.face_118);
        FACE_MAP.put("[转圈]", R.mipmap.face_119);
        FACE_MAP.put("[鄙视]", R.mipmap.face_120);
        FACE_MAP.put("[酷]", R.mipmap.face_121);
        FACE_MAP.put("[钞票]", R.mipmap.face_122);
        FACE_MAP.put("[钻戒]", R.mipmap.face_123);
        FACE_MAP.put("[闪电]", R.mipmap.face_124);
        FACE_MAP.put("[闭嘴]", R.mipmap.face_125);
        FACE_MAP.put("[闹钟]", R.mipmap.face_126);
        FACE_MAP.put("[阴险]", R.mipmap.face_127);
        FACE_MAP.put("[难过]", R.mipmap.face_128);
        FACE_MAP.put("[雨伞]", R.mipmap.face_129);
        FACE_MAP.put("[青蛙]", R.mipmap.face_130);
        FACE_MAP.put("[面条]", R.mipmap.face_131);
        FACE_MAP.put("[鞭炮]", R.mipmap.face_132);
        FACE_MAP.put("[风车]", R.mipmap.face_133);
        FACE_MAP.put("[飞吻]", R.mipmap.face_134);
        FACE_MAP.put("[飞机]", R.mipmap.face_135);
        FACE_MAP.put("[饥饿]", R.mipmap.face_136);
        FACE_MAP.put("[香蕉]", R.mipmap.face_137);
        FACE_MAP.put("[骷髅]", R.mipmap.face_138);
        FACE_MAP.put("[麦克风]", R.mipmap.face_139);
        FACE_MAP.put("[麻将]", R.mipmap.face_140);
        FACE_MAP.put("[鼓掌]", R.mipmap.face_141);
        FACE_MAP.put("[龇牙]", R.mipmap.face_142);
//        FACE_MAP.put("[微笑]", R.mipmap.face_001);
//        FACE_MAP.put("[色]", R.mipmap.face_002);
//        FACE_MAP.put("[发呆]", R.mipmap.face_003);
//        FACE_MAP.put("[抽烟]", R.mipmap.face_004);
//        FACE_MAP.put("[抠鼻]", R.mipmap.face_005);
//        FACE_MAP.put("[哭]", R.mipmap.face_006);
//        FACE_MAP.put("[发怒]", R.mipmap.face_007);
//        FACE_MAP.put("[呲牙]", R.mipmap.face_008);
//        FACE_MAP.put("[睡]", R.mipmap.face_009);
//        FACE_MAP.put("[害羞]", R.mipmap.face_010);
//        FACE_MAP.put("[调皮]", R.mipmap.face_011);
//        FACE_MAP.put("[晕]", R.mipmap.face_012);
//        FACE_MAP.put("[衰]", R.mipmap.face_013);
//        FACE_MAP.put("[闭嘴]", R.mipmap.face_014);
//        FACE_MAP.put("[指点]", R.mipmap.face_015);
//        FACE_MAP.put("[关注]", R.mipmap.face_016);
//        FACE_MAP.put("[搞定]", R.mipmap.face_017);
//        FACE_MAP.put("[胜利]", R.mipmap.face_018);
//        FACE_MAP.put("[无奈]", R.mipmap.face_019);
//        FACE_MAP.put("[打脸]", R.mipmap.face_020);
//        FACE_MAP.put("[大笑]", R.mipmap.face_021);
//        FACE_MAP.put("[哈欠]", R.mipmap.face_022);
//        FACE_MAP.put("[害怕]", R.mipmap.face_023);
//        FACE_MAP.put("[喜欢]", R.mipmap.face_024);
//        FACE_MAP.put("[困]", R.mipmap.face_025);
//        FACE_MAP.put("[疑问]", R.mipmap.face_026);
//        FACE_MAP.put("[伤心]", R.mipmap.face_027);
//        FACE_MAP.put("[鼓掌]", R.mipmap.face_028);
//        FACE_MAP.put("[得意]", R.mipmap.face_029);
//        FACE_MAP.put("[捂嘴]", R.mipmap.face_030);
//        FACE_MAP.put("[惊恐]", R.mipmap.face_031);
//        FACE_MAP.put("[思考]", R.mipmap.face_032);
//        FACE_MAP.put("[吐血]", R.mipmap.face_033);
//        FACE_MAP.put("[卖萌]", R.mipmap.face_034);
//        FACE_MAP.put("[嘘]", R.mipmap.face_035);
//        FACE_MAP.put("[生气]", R.mipmap.face_036);
//        FACE_MAP.put("[尴尬]", R.mipmap.face_037);
//        FACE_MAP.put("[笑哭]", R.mipmap.face_038);
//        FACE_MAP.put("[口罩]", R.mipmap.face_039);
//        FACE_MAP.put("[斜眼]", R.mipmap.face_040);
//        FACE_MAP.put("[酷]", R.mipmap.face_041);
//        FACE_MAP.put("[脸红]", R.mipmap.face_042);
//        FACE_MAP.put("[大叫]", R.mipmap.face_043);
//        FACE_MAP.put("[眼泪]", R.mipmap.face_044);
//        FACE_MAP.put("[见钱]", R.mipmap.face_045);
//        FACE_MAP.put("[嘟]", R.mipmap.face_046);
//        FACE_MAP.put("[吓]", R.mipmap.face_047);
//        FACE_MAP.put("[开心]", R.mipmap.face_048);
//        FACE_MAP.put("[想哭]", R.mipmap.face_049);
//        FACE_MAP.put("[郁闷]", R.mipmap.face_050);
//        FACE_MAP.put("[互粉]", R.mipmap.face_051);
//        FACE_MAP.put("[赞]", R.mipmap.face_052);
//        FACE_MAP.put("[拜托]", R.mipmap.face_053);
//        FACE_MAP.put("[唇]", R.mipmap.face_054);
//        FACE_MAP.put("[粉]", R.mipmap.face_055);
//        FACE_MAP.put("[666]", R.mipmap.face_056);
//        FACE_MAP.put("[玫瑰]", R.mipmap.face_057);
//        FACE_MAP.put("[黄瓜]", R.mipmap.face_058);
//        FACE_MAP.put("[啤酒]", R.mipmap.face_059);
//        FACE_MAP.put("[无语]", R.mipmap.face_060);
//        FACE_MAP.put("[纠结]", R.mipmap.face_061);
//        FACE_MAP.put("[吐舌]", R.mipmap.face_062);
//        FACE_MAP.put("[差评]", R.mipmap.face_063);
//        FACE_MAP.put("[飞吻]", R.mipmap.face_064);
//        FACE_MAP.put("[再见]", R.mipmap.face_065);
//        FACE_MAP.put("[拒绝]", R.mipmap.face_066);
//        FACE_MAP.put("[耳机]", R.mipmap.face_067);
//        FACE_MAP.put("[抱抱]", R.mipmap.face_068);
//        FACE_MAP.put("[嘴]", R.mipmap.face_069);
//        FACE_MAP.put("[露牙]", R.mipmap.face_070);
//        FACE_MAP.put("[黄狗]", R.mipmap.face_071);
//        FACE_MAP.put("[灰狗]", R.mipmap.face_072);
//        FACE_MAP.put("[蓝狗]", R.mipmap.face_073);
//        FACE_MAP.put("[狗]", R.mipmap.face_074);
//        FACE_MAP.put("[脸黑]", R.mipmap.face_075);
//        FACE_MAP.put("[吃瓜]", R.mipmap.face_076);
//        FACE_MAP.put("[绿帽]", R.mipmap.face_077);
//        FACE_MAP.put("[汗]", R.mipmap.face_078);
//        FACE_MAP.put("[摸头]", R.mipmap.face_079);
//        FACE_MAP.put("[阴险]", R.mipmap.face_080);
//        FACE_MAP.put("[擦汗]", R.mipmap.face_081);
//        FACE_MAP.put("[瞪眼]", R.mipmap.face_082);
//        FACE_MAP.put("[疼]", R.mipmap.face_083);
//        FACE_MAP.put("[鬼脸]", R.mipmap.face_084);
//        FACE_MAP.put("[拇指]", R.mipmap.face_085);
//        FACE_MAP.put("[亲]", R.mipmap.face_086);
//        FACE_MAP.put("[大吐]", R.mipmap.face_087);
//        FACE_MAP.put("[高兴]", R.mipmap.face_088);
//        FACE_MAP.put("[敲打]", R.mipmap.face_089);
//        FACE_MAP.put("[加油]", R.mipmap.face_090);
//        FACE_MAP.put("[吐]", R.mipmap.face_091);
//        FACE_MAP.put("[握手]", R.mipmap.face_092);
//        FACE_MAP.put("[18禁]", R.mipmap.face_093);
//        FACE_MAP.put("[菜刀]", R.mipmap.face_094);
//        FACE_MAP.put("[威武]", R.mipmap.face_095);
//        FACE_MAP.put("[给力]", R.mipmap.face_096);
//        FACE_MAP.put("[爱心]", R.mipmap.face_097);
//        FACE_MAP.put("[心碎]", R.mipmap.face_098);
//        FACE_MAP.put("[便便]", R.mipmap.face_099);
//        FACE_MAP.put("[礼物]", R.mipmap.face_100);
//        FACE_MAP.put("[生日]", R.mipmap.face_101);
//        FACE_MAP.put("[喝彩]", R.mipmap.face_102);
//        FACE_MAP.put("[雷]", R.mipmap.face_103);

        FACE_LIST = new ArrayList<>();
        for (Map.Entry<String, Integer> entry : FACE_MAP.entrySet()) {
            FACE_LIST.add(entry.getKey());
        }
    }

    public static List<String> getFaceList() {
        return FACE_LIST;
    }

    public static Integer getFaceImageRes(String key) {
        return FACE_MAP.get(key);
    }
}
